import { CompanionPayload } from "../services/companion.service.js";

export const companions: CompanionPayload[] = [
    {
        name: 'Codey, the Logic Hacker',
        subject: 'Coding',
        topic: 'Intro to If-Else Statements',
        duration: 30,
        language: 'English',
        style: 'interactive',
        voiceType: 'male-energetic',
        icon: '⌨️',
        iconColor: 'bg-orange-100 border-orange-200',
    },
    {
        name: 'Nova, the JavaScript Guide',
        subject: 'Coding',
        topic: 'Understanding Variables & Scope',
        duration: 25,
        language: 'English',
        style: 'clear',
        voiceType: 'female-clear',
        icon: '🧠',
        iconColor: 'bg-yellow-100 border-yellow-200',
    },
    {
        name: 'Reactron',
        subject: 'Frontend Development',
        topic: 'React Components & Props',
        duration: 35,
        language: 'English',
        style: 'structured',
        voiceType: 'male-calm',
        icon: '⚛️',
        iconColor: 'bg-sky-100 border-sky-200',
    },
    {
        name: 'Byte, the Backend Builder',
        subject: 'Backend',
        topic: 'APIs & Request Lifecycle',
        duration: 40,
        language: 'English',
        style: 'technical',
        voiceType: 'male-deep',
        icon: '🛠️',
        iconColor: 'bg-slate-100 border-slate-200',
    },
    {
        name: 'Mongo, The Database Guide',
        subject: 'Databases',
        topic: 'Intro to SQL & Tables',
        duration: 30,
        language: 'English',
        style: 'explanatory',
        voiceType: 'female-soft',
        icon: '🗄️',
        iconColor: 'bg-emerald-100 border-emerald-200',
    },
    {
        name: 'Shield, The Security Guide',
        subject: 'Security',
        topic: 'Authentication & JWT Basics',
        duration: 35,
        language: 'English',
        style: 'practical',
        voiceType: 'male-serious',
        icon: '🔐',
        iconColor: 'bg-red-100 border-red-200',
    },
    {
        name: 'Pixel, The UI/UX Guide',
        subject: 'UI/UX',
        topic: 'Designing Accessible Interfaces',
        duration: 25,
        language: 'English',
        style: 'friendly',
        voiceType: 'female-warm',
        icon: '🎨',
        iconColor: 'bg-pink-100 border-pink-200',
    },
    {
        name: 'Cloudy, The DevOps Guide',
        subject: 'DevOps',
        topic: 'Deploying Apps with Docker',
        duration: 45,
        language: 'English',
        style: 'step-by-step',
        voiceType: 'male-informative',
        icon: '☁️',
        iconColor: 'bg-indigo-100 border-indigo-200',
    },
    {
        name: 'Algo, The Algorithm Guide',
        subject: 'Computer Science',
        topic: 'Big-O Notation Explained',
        duration: 30,
        language: 'English',
        style: 'logical',
        voiceType: 'male-neutral',
        icon: '📊',
        iconColor: 'bg-purple-100 border-purple-200',
    },
    {
        name: 'Mentor Max, The Career Guide',
        subject: 'Career',
        topic: 'How to Think Like a Software Engineer',
        duration: 20,
        language: 'English',
        style: 'motivational',
        voiceType: 'male-warm',
        icon: '🚀',
        iconColor: 'bg-green-100 border-green-200',
    },
];